[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
